### ISSUE TITLE
There is no way to input LocalDates in the insight

### ISSUE THREAD

**Issue by bekand** [finos/morphir-elm#1015]
**Is your feature request related to a problem? Please describe.**
Currently we don't have a value editor that is able to handle date inputs. This means that if a function defines one of it's parameters as "LocalDate", we are not able to test it

**Describe the solution you'd like**
Similar to other basic types supported by Morphir, a dedicated LocalDate editor (a text input specifying an explicit date format like for example dd-mm-yyyy, or a date picker) should be implemented.

**Comment by edwardpeters** [comment]
Has this been resolved? It seems to work now.

**Comment by stephengoldbaum** [comment]
Yes, thanks for the reminder
