### ISSUE TITLE
Two links appear to be broken in the readme

### ISSUE THREAD

**Issue by MartinSStewart** [finos/morphir-elm#119]
![image](https://user-images.githubusercontent.com/5068391/90479952-c9963b80-e12f-11ea-8bc1-059612e6b3c2.png)
The two links underlined in red lead to 404 pages.

**Comment by stephengoldbaum** [comment]
Hi Martin.  Thank you for pointing this out.  This is actually part of the transition of Morphir to FINOS (http://finos.org).  Those links will work once the transition is complete.

**Comment by AttilaMihaly** [comment]
This is fixed now.
