### ISSUE TITLE
CLI make and gen have different default behaviors

### ISSUE THREAD

**Issue by stephengoldbaum** [finos/morphir-elm#145]
Running _moprhir-elm_ make relies on the morphir.json configuration file by default.  Running _morphir-elm gen_ defaults to expecting a pipe and takes the configuration file as an optional argument.  It should probably match the make command for consistency and leave the piping as an option.

**Comment by AttilaMihaly** [comment]
There are two JSON files at play here: 

- The `morphir.json` that `morphir-elm make` expects is a descriptor that the Elm frontend uses to be able to find the Elm sources and to add extra package information.
- The JSON that `morphir-elm make` outputs and `morphir-elm gen` expects as input is the Morphir IR. They use **stdout/stdin** by default and they have `-o` and `-i` options to specify the a file if that's what the user prefers.

 Considering the above I think the behavior is consistent but I understand how it can be confusing. To simplify I suggest removing the  **stdout/stdin** path and make the `-o`/`-i` options required. I'll also add note to the docs to further clarify the purpose of each JSON.
