### ISSUE TITLE
Implement native functions for all in-scope SDK functions

### ISSUE THREAD

**Issue by AttilaMihaly** [finos/morphir-elm#199]
# Scope 
SDK functions that are in the initial scope:

- [ ] List.map
- [ ] List.sum
- [ ] List.append
- [ ] Basics.add
- [ ] Basics.subtract
- [ ] Basics.multiply
- [ ] Basics.divide
- [x] Basics.equal
- [x] Basics.and
- [x] Basics.or
- [ ] Basics.lessThan
- [ ] String.concat

# Implementation Details

Basics functions should be added here: 
https://github.com/finos/morphir-elm/blob/56e0816c6542274cefde664e2b341fa10cca8093/src/Morphir/IR/SDK/Basics.elm#L127-L187

List and String functions should be added to the below files as anew function:
https://github.com/finos/morphir-elm/blob/56e0816c6542274cefde664e2b341fa10cca8093/src/Morphir/IR/SDK/List.elm#L111
https://github.com/finos/morphir-elm/blob/56e0816c6542274cefde664e2b341fa10cca8093/src/Morphir/IR/SDK/String.elm#L94
And added to the list of references here:
https://github.com/finos/morphir-elm/blob/56e0816c6542274cefde664e2b341fa10cca8093/src/Morphir/IR/SDK.elm#L82-L83

# Definition of done
There should be native functions covering each of the SDK functions mentioned in the scope.

**Comment by piyush-gupta1999** [comment]
I am not able to understand the native functions clearly and how to use them to write a new functionality for List and string.

**Comment by AttilaMihaly** [comment]
I'm adding more documentation. Stay tuned! #222
