### ISSUE TITLE
The IR should include the Version

### ISSUE THREAD

**Issue by DamianReeves** [finos/morphir-elm#22]
**What?**
The IR should include the version of the IR as some sort of metadata field.

**Why?**
There will, be a need to version the IR, so embedding the IR version within the IR makes it possible to support this versioning in front-end and back-end tools targeting the IR.

**Comment by AttilaMihaly** [comment]
Makes sense. We ran into cases in the past where the tooling just failed because breaking format changes but didn't explicitly say it was because of that. So I'll add the version number before we make more changes to the IR and fail fast in the tooling with a nice error message.
