### ISSUE TITLE
Type inference issue in "morphir-elm make" when having import of a type alias of Float

### ISSUE THREAD

**Issue by msigmond** [finos/morphir-elm#227]
**Describe the bug**
I used a type alias of Float in a function.
The "morphir-elm make" command succeeded as long as the type alias was declared in the same file as the function.
However once I moved the type alias declaration into another module, and then imported that module, I got an error.

**To Reproduce**
Here is an example:
```elm
type alias FloatAlias =
  Float


fun : FloatAlias -> FloatAlias
fun f =
  if f <= 3.14 then
    f
  else
    f
```

Move the type alias into another module, import that module where `fun` is, and then `fun` compilation will produce the following error message:
```
Error: ["type_error",[["value_type_error",["fun"],["could_not_unify",["ref_mismatch"],["meta_ref",[[["com"],["m","s"],["common"]],["float","alias"]]],["meta_ref",[[["morphir"],["s","d","k"]],[["basics"]],["float"]]]]]]]
```

**Comment by AttilaMihaly** [comment]
I tried reproducing this but it seems to work with the latest codebase. Can you confirm the version you were using or retry with the latest?

**Comment by AttilaMihaly** [comment]
Discussed offline and managed to reproduce by moving the alias out to a separate file and not mentioning that module in the list of exposed modules.
