### ISSUE TITLE
Scala Code-Gen: When generating enums and sealed trait hierarchies from custom types the cases should be generated within the companion object

### ISSUE THREAD

**Issue by DamianAtWork** [finos/morphir-elm#236]
## Component

Scala Code Gen

## Change Request
When generating enums and sealed trait hierarchies from custom types the cases should be generated within the companion object.

## Current Behavior
Currently a model like this:

```elm
module Finos.Finance.DebitOrCredit exposing (DebitOrCredit(..), credit, debit)


type DebitOrCredit
    = Debit
    | Credit


debit : DebitOrCredit
debit =
    Debit


credit : DebitOrCredit
credit =
    Credit

```

Generates this:

```scala
package finos.finance
/** Generated based on DebitOrCredit
*/
object DebitOrCredit{
  sealed trait DebitOrCredit {
  
    
  
  }
  
  case object Debit extends finos.finance.DebitOrCredit.DebitOrCredit{}
  
  case object Credit extends finos.finance.DebitOrCredit.DebitOrCredit{}
  
  def credit: finos.finance.DebitOrCredit.DebitOrCredit =
    finos.finance.DebitOrCredit.Credit
  
  def debit: finos.finance.DebitOrCredit.DebitOrCredit =
    finos.finance.DebitOrCredit.Debit
}
```

## Desired State

It is best to generate the `Debit` and `Credit` cases of the above example within the companion object of `DebitOrCredit`. This is the recommended practice for Scala and is the form it takes in Scala 3 which has a more appropriate encoding for this with `enum`. This enum encoding also generated down to the nesting I am suggesting.

```scala
object DebitOrCredit {
        sealed trait DebitOrCredit
    object DebitOrCredit {
        case object Debit extends morganstanley.finance.DebitOrCredit.DebitOrCredit{}  
        case object Credit extends morganstanley.finance.DebitOrCredit.DebitOrCredit{}
    }
}
```

**Comment by AttilaMihaly** [comment]
Just a note to help with the implementation: When you are changing how the type is generated you will also need to change the code that refers to the constructors. Currently it simply maps the Elm name to the Scala one:
https://github.com/finos/morphir-elm/blob/ff658d9164060e2e64fa2463b639795877983dd1/src/Morphir/Scala/Backend.elm#L460-L473

With this change the name will have to be derived by looking up the corresponding type. You should also remember that a constructor might refer to a record type alias so you will have different naming for those.

**Comment by DamianAtWork** [comment]
> With this change the name will have to be derived by looking up the corresponding type. You should also remember that a constructor might refer to a record type alias so you will have different naming for those.

Thanks for pointing this out.

I think one thing that can make this change a bit safer is if we generated constructors at the same level as the case class is generated now.

So the generated code from the example would look more like:

```scala
package finos.finance
object DebitOrCredit{
  sealed trait DebitOrCredit 
 object DebitOrCredit {
        case object Debit extends finos.finance.DebitOrCredit.DebitOrCredit{}  
        case object Credit extends finos.finance.DebitOrCredit.DebitOrCredit{}
    }

  val Credit = finos.finance.DebitOrCredit.DebitOrCredit.Credit
  val Debit = finos.finance.DebitOrCredit.DebitOrCredit.Debit

  def credit: finos.finance.DebitOrCredit.DebitOrCredit =
    finos.finance.DebitOrCredit.Credit
  
  def debit: finos.finance.DebitOrCredit.DebitOrCredit =
    finos.finance.DebitOrCredit.Debit
}
```

**Comment by DamianAtWork** [comment]
I'm wondering whether or not the `Pattern` in `ValueDecl` for the scala AST needs to be a `Maybe`.

To represent:

```scala
val Credit = finos.finance.DebitOrCredit.DebitOrCredit.Credit
```
It would seem I don't need a `Pattern` unless this is considered an `UnapplyMatch` is that the case?

**Comment by DamianAtWork** [comment]
Nevermind, I think I figured it out.

**Comment by AttilaMihaly** [comment]
Not sure if that's the conclusion you came to but I think it should be a `NamedMatch`.
