### ISSUE TITLE
Add missing mappings for in-scope operators

### ISSUE THREAD

**Issue by AttilaMihaly** [finos/morphir-elm#269]
- [ ] Handle non-SDK functions by showing their local name.
  - This needs to be added to two places: Apply, Reference.
- [ ] Handle Lists by recursively calling the same function for each value and concatenating the result with `,` as a separator.
- [ ] Handle constructors by showing the local name and arguments separated by spaces.

**Comment by piyush-gupta1999** [comment]
After the last commit, It seems like we are no longer using Graphviz for UI. Then why we need to implement these functionalities.

**Comment by AttilaMihaly** [comment]
> After the last commit, It seems like we are no longer using Graphviz for UI. Then why we need to implement these functionalities.

I completely agree. At the same time some of these apply to the HTML-only decision tree as well. I'll create new issues to organize things a bit.
