### ISSUE TITLE
Implement visualization for boolean expressions

### ISSUE THREAD

**Issue by AttilaMihaly** [finos/morphir-elm#291]
Create a specific visualization component for boolean expressions. The main layout should be organized ANDs and ORs. Given the expression `foo == 0 || bar || baz` the visualization should be similar to this:

```
 foo = 0
--- or ---
    bar
--- or ---
    baz
```

This can be achieved using https://package.elm-lang.org/packages/mdgriffith/elm-ui/latest/Element#column.

The component should handle nested expressions by alternating vertical and horizontal layouts:
```
 foo = 0
--- or ---
        | 
   A   and   B
        |
--- or ---
    baz
```

The top level should always be laid out vertically regardless of whether it's OR or AND.

The component should be invoked by checking the type of the value passed in here: https://github.com/finos/morphir-elm/blob/dd1506f7208c87e15357db2813caa4e73c3d0707/src/Morphir/Visual/ViewValue.elm#L22

`SDK.boolType` is the value type to look for. To get the value type out of a `Value () (Type ())` you can use the utility function here:  https://github.com/finos/morphir-elm/blob/dd1506f7208c87e15357db2813caa4e73c3d0707/src/Morphir/IR/Value.elm#L360

**Comment by AttilaMihaly** [comment]
Sample:

```elm
original =
  a || b || (c && d)
  

irVersion : Value
irVersion =
  or a (or b (and c d))
  

visual =
  or [ a, b, (and [ c, d ]) ]
  
  
type BoolNode 
  = BoolNode AndOr (List BoolNode)
  | Leaf Value
  
  
type AndOr = And | Or  


visual2 : BoolNode
visual2 =
  BoolNode Or [ Leaf a, Leaf b, BoolNode And [ Leaf c, Leaf d ] ]
```

**Comment by piyush-gupta1999** [comment]
If I have the BoolNode expression of the whole value Expression.
I am trying to visualize it.
My Approach is 

`evaluateBoolNode : (Context -> Dict Name RawValue -> TypedValue -> Element msg) -> BoolNode -> Element msg`
`evaluateBoolNode viewValue boolNode =`
   
     case boolNode of
        BoolNode andOr nodeList ->
            let
                evaluatedList =
                    nodeList
                        |> List.map
                            (\listValue ->
                                evaluateBoolNode viewValue listValue
                            )
            in
            case andOr of
                And ->
                    Element.column
                        [ Background.color (rgb 0 0.5 0)
                        , Border.color (rgb 0 0.7 0)

                        -- Some More Attributes
                        ]
                        evaluatedList

                Or ->
                    Element.row
                        [ Background.color (rgb 0 0.5 0)
                        , Border.color (rgb 0 0.7 0)
                        ]
                        evaluatedList

        -- Something to Do with the layout part But not able to figure out where How to show the whole list in the required output.
        Leaf value ->
            viewValue value


Now I need some suggestions and hints to start the visualization.
