### ISSUE TITLE
Treat number literals as generic numbers instead of specific representations like Int or Float

### ISSUE THREAD

**Issue by AttilaMihaly** [finos/morphir-elm#294]
Currently we differentiate `Int` and `Float` literals in the IR:
https://github.com/finos/morphir-elm/blob/552d7d65682bdb48cbce9e80ea95022011bc1aed/src/Morphir/IR/Literal.elm#L39-L40

As it turns out this causes more harm than good because Elm treats `Int` literals as instances of the `number` type class which will be treated as `Int` or `Float` depending on the use-case.

**Comment by DamianReeves** [comment]
That is Elm, but what about something like F#. I'd hate to cut the expressivity of Morphir for a single front-end.

**Comment by AttilaMihaly** [comment]
>That is Elm, but what about something like F#. I'd hate to cut the expressivity of Morphir for a single front-end.

The wording on the issue is a bit confusing so I changed it. 

The type of whole number literals being number is not an Elm thing. Haskell uses the same approach because just writing down `1` should not mean that you want an `Int`. `1` could mean a lot of things from various integer types through float to decimal or even rational. So the fundamental issue is that the text representation is ambiguous. 

What makes things even more difficult is that we use literals both as a way to represent constants that are part of the business logic and as a way to work with data. For constants in the business logic we want to be a bit more abstract so a float makes little sense there while in the data it's more desirable to have specific representation formats like that.

So keeping all that in mind I suggest we keep the existing `IntLiteral` and `FloatLiteral` representations as they align nicely with existing technologies but we make it easier to deal with them consistently.

The biggest issue we have currently is in the `Interpreter` where we have to allow `IntLiteral` in place of any `FloatLiteral` since `1` is actually a valid `Float`. The first issue we have is that we cannot match on "number literals" so we end up having to cover a baunch of specific cases: https://github.com/finos/morphir-elm/blob/2e198f3ea0c7d0cff1ffff750adc22dc44693487/src/Morphir/IR/SDK/Basics.elm#L413-L423

We also have to convert `Int`s to `Float`s in many specific cases. We can solve both issues by introducing a new `NumberLiteral` abstraction to replace this: https://github.com/finos/morphir-elm/blob/2e198f3ea0c7d0cff1ffff750adc22dc44693487/src/Morphir/IR/Literal.elm#L35-L40

With something like this:

```elm
type Literal
    = BoolLiteral Bool
    | CharLiteral Char
    | StringLiteral String
    | NumberLiteral Number

type Number
    = Int Int
    | Float Float
```

**Comment by AttilaMihaly** [comment]
The interpreter issue that motivated this suggestion was fixed by changing `IntLiteral` into `FloatLiteral` when the type inference decides that the literal should be of float type. The name `IntLiteral` is still slightly confusing since it doesn't necessarily mean a value of type `Int`. The ideal solution would be to rename it to `WholeNumberLiteral` so will close this and open a new issue for that.

**Comment by AttilaMihaly** [comment]
Created #399 based on the above
