### ISSUE TITLE
Unification rules error with Morphir.SDK.Rule

### ISSUE THREAD

**Issue by blake-charles** [finos/morphir-elm#409]
When trying to run `morphir-elm make` with the following model
https://github.com/blake-charles/morphir-elm/blob/14538a61df1bddcbf2993df39e017980be732aa3/tests-integration/reference-model/src/Morphir/Reference/Model/Issues/PatternModel/BasicEnum.elm
https://github.com/blake-charles/morphir-elm/blob/14538a61df1bddcbf2993df39e017980be732aa3/tests-integration/reference-model/src/Morphir/Reference/Model/Issues/PatternModel/OtherBasicEnum.elm
https://github.com/blake-charles/morphir-elm/blob/14538a61df1bddcbf2993df39e017980be732aa3/tests-integration/reference-model/src/Morphir/Reference/Model/Issues/PatternModel/BasicRule.elm

 the following error occurs:
`PS C:\Users\Administrator\Documents\morphir-elm\morphir-elm\tests-integration\reference-model> morphir-elm make
Error: [
  [
    "errors_in_source_file",
    "Issues.PatternModel.BasicRule",
    [
      {
        "errorMessage": "Type error in value 'basicRuleSet': Could not unify 'Morphir.SDK:Rule:rule var_1_1 var_1_2' with '{ basicEnum : Morphir.Reference.Model:Issues.PatternModel.BasicEnum:basicEnum, id : Morphir.SDK:String:string, otherBasicEnum : Morphir.Reference.Model:Issues.PatternModel.OtherBasicEnum:otherBasicEnum } as Morphir.Reference.Model:Issues.PatternModel.BasicRule:basicRule -> Morphir.SDK:Maybe:maybe Morphir.SDK:String:string' because there are no unification rules to apply",
        "sourceLocations": []
      }
    ]
  ]
]`

**Comment by AttilaMihaly** [comment]
Here are the specific declarations that are causing the error for reference:

```elm
type alias BasicRule =
    { basic_enum : BasicEnum
    , other_basic_enum : OtherBasicEnum
    , id : String
    }


basicRuleSet : Rule BasicRule String
basicRuleSet =
    Rule.chain
        [ rule (is One) (is A) any "foo"
        , rule (is One) (anyOf [ B, C, D ]) any "bar"
        , rule (is One) any any "foobar"
        , rule (anyOf [ Two, Three, Four ]) any any "baz"
        , rule any any any "foobarbaz"
        ]


rule : (BasicEnum -> Bool) -> (OtherBasicEnum -> Bool) -> (String -> Bool) -> String -> BasicRule -> Maybe String
rule matchBasicEnum matchOtherBasicEnum matchId result data =
    if
        matchBasicEnum data.basic_enum
            && matchOtherBasicEnum data.other_basic_enum
            && matchId data.id
    then
        Just result

    else
        Nothing
```

And here's the error in a formatted version:

```js
[
   [
      "errors_in_source_file",
      "Issues.PatternModel.BasicRule",
      [
         {
            "errorMessage":"Type error in value 'basicRuleSet': Could not unify 'Morphir.SDK:Rule:rule var_1_1 var_1_2' with '{ basicEnum : Morphir.Reference.Model:Issues.PatternModel.BasicEnum:basicEnum, id : Morphir.SDK:String:string, otherBasicEnum : Morphir.Reference.Model:Issues.PatternModel.OtherBasicEnum:otherBasicEnum } as Morphir.Reference.Model:Issues.PatternModel.BasicRule:basicRule -> Morphir.SDK:Maybe:maybe Morphir.SDK:String:string' because there are no unification rules to apply",
            "sourceLocations":[
               
            ]
         }
      ]
   ]
]
```

As a first step I'll try to reproduce and shrink the problem.
