### ISSUE TITLE
Display the list of test cases in Morphir Web

### ISSUE THREAD

**Issue by AttilaMihaly** [finos/morphir-elm#411]
The goal of this task is to read the test cases from the test suite JSON file defined in #410 and display it on the function specific route of Morphir Web.

Here are the specific subtasks:

- [ ] Update the `morphir-elm develop` JavaScript wrapper to serve a `morphir-tests.json` file similar to how it already does for `morphir-ir.json`.
- [ ] Add an HTTP request to download the `morphir-tests.json` in `DevelopApp.elm`.
- [ ] Decode the JSON and display the list of test cases in the page.

**Comment by piyush-gupta1999** [comment]
The First Version of the Testing Framework is released.
