### ISSUE TITLE
Developer tool binding to http://undefined:undefined

### ISSUE THREAD

**Issue by stephengoldbaum** [finos/morphir-elm#608]
**Describe the bug**
Running the morphir-elm develop tool binds to host:port undefined:undefined

**To Reproduce**
1. From command line type: morphir-elm develop
2. Error is: Developer server listening at http://undefined:undefined

**Expected behavior**
Developer server listening at http://0.0.0.0:3000

**Comment by AttilaMihaly** [comment]
Thank you for reporting. This is a regression that was introduced in the latest release. The team identified this last night and working on a fix now.
