### ISSUE TITLE
Morphir Scala code generator does not generate Key class

### ISSUE THREAD

**Issue by willms2021** [finos/morphir-elm#666]
**Is your feature request related to a problem? Please describe.**
In Morphir SDK, we have a class called Key.elm.  If we use it in our elm code and generate the code with option -c, it should be generating a Key.scala class but it doesn't.

**Describe the solution you'd like**
If our elm code uses Morphir.SDK.Key and we generate code with "morphir-gen -c" option, it should generate a Key.scala class in the output.

**Comment by AttilaMihaly** [comment]
Resolved by https://github.com/finos/morphir-jvm/issues/106
