### ISSUE TITLE
Update GitHub Actions Release workflow to publish to npm

### ISSUE THREAD

**Issue by DamianReeves** [finos/morphir-elm#80]
Our current release workflow creates a release and adds morphir-elm as a single javascript file asset to that release. We should also do NPM publication as a part of that.

- [ ] - Look into how we can give GitHub actions permissions to publish npm packages for us
- [ ] - Add the npm publish step as part of our release workflow

**Comment by AttilaMihaly** [comment]
Duplicate of #108
