### ISSUE TITLE
Running morphir-elm make on the morphir-elm codebase does not work

### ISSUE THREAD

**Issue by DamianReeves** [finos/morphir-elm#882]
**Describe the bug**
Running morphir-elm make on the morphir-elm codebase does not work, it errors with a "Resolve error"

**To Reproduce**
1. Clone `finos/morphir-elm` locally
2. Install the `morphir-elm` tooling using `npm install -g morphir-elm`
3. Run `morphir-elm make -t` in the root of the morphir-elm codebase

```
❯ morphir-elm make -t
Compiled in DEV mode. Follow the advice at https://elm-lang.org/0.19.1/optimize for better performance and smaller assets.
[2022-09-06T20:25:56.010Z] Error: [
  [
    "errors_in_source_file",
    "src/Morphir/SDK/Decimal.elm",
    [
      {
        "errorMessage": "Resolve error: Could not find module 'decimal",
        "sourceLocations": [
          {
            "start": {
              "row": 114,
              "column": 5
            },
            "end": {
              "row": 114,
              "column": 14
            }
          }
        ]
      }
    ]
  ]
]
```

**Expected behavior**
Expect make to work and the `morphir-ir.json` file to be produced.

**Desktop (please complete the following information):**
 - OS: iOS
 - Version:  morphir-elm version 2.65.8

**Additional context**

**Comment by DamianReeves** [comment]
@AttilaMihaly or @stephengoldbaum  can you have someone take a look at this?

**Comment by DamianReeves** [comment]
Cool. I'm actually trying to generate the IR using the tooling, is there a workaround I can do in the interim?

**Comment by AttilaMihaly** [comment]
I thought just renaming the problematic file temporarily would resolve the issue but it brought up others. I think your best bet is to wait for our fix. We'll try to get it in this week.

**Comment by AttilaMihaly** [comment]
It looks like it's going to take more time to fix this. We recently rolled out a new incremental version of the Elm frontend which adds further complexity to this. I'll let you know once we have a solution.

**Comment by DamianReeves** [comment]
Last I checked this is working now.
