### ISSUE TITLE
Include abs in the Number type class.

### ISSUE THREAD

**Issue by DamianReeves** [finos/morphir-elm#91]
Include abs in the Number type class.

https://github.com/Morgan-Stanley/morphir-elm/blob/2dfd49aa61448374d4f9045e7aa54ffc660b88c9/src/Morphir/IR/SDK/Comparison.elm#L1

**Comment by AttilaMihaly** [comment]
This is done:
https://github.com/finos/morphir-elm/blob/5e18e70bd4631aea1d1b677be04b62de3069a5eb/src/Morphir/IR/SDK/Basics.elm#L80
